In [26]:
import pandas as pd
import numpy as np

df=pd.read_csv("social_anxiety_dataset.csv")

df.shape
df.columns

Index(['Age', 'Gender', 'Occupation', 'Sleep Hours',
       'Physical Activity (hrs/week)', 'Caffeine Intake (mg/day)',
       'Alcohol Consumption (drinks/week)', 'Smoking',
       'Family History of Anxiety', 'Stress Level (1-10)', 'Heart Rate (bpm)',
       'Breathing Rate (breaths/min)', 'Sweating Level (1-5)', 'Dizziness',
       'Medication', 'Therapy Sessions (per month)', 'Recent Major Life Event',
       'Diet Quality (1-10)', 'Anxiety Level (1-10)', 'Target', 'is_Anxious',
       'Therapy History'],
      dtype='object')

In [27]:
df.shape

(2030, 22)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2030 entries, 0 to 2029
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1968 non-null   float64
 1   Gender                             1911 non-null   object
 2   Occupation                         2030 non-null   object
 3   Sleep Hours                        1994 non-null   float64
 4   Physical Activity (hrs/week)       2030 non-null   float64
 5   Caffeine Intake (mg/day)           1936 non-null   float64
 6   Alcohol Consumption (drinks/week)  2030 non-null   int64
 7   Smoking                            1924 non-null   object
 8   Family History of Anxiety          2030 non-null   object
 9   Stress Level (1-10)                2030 non-null   int64
 10  Heart Rate (bpm)                   2030 non-null   int64
 11  Breathing Rate (breaths/min)       2030 non-null   int64
 12  Sweating Level (1-5)               2030 non-null   int64
 13  Dizziness                          2030 non-null   object
 14  Medication                         1921 non-null   object
 15  Therapy Sessions (per month)       2030 non-null   int64
 16  Recent Major Life Event            2030 non-null   object
 17  Diet Quality (1-10)                1952 non-null   float64
 18  Anxiety Level (1-10)               2030 non-null   float64
 19  Target                             2030 non-null   int64
 20  is_Anxious                         2030 non-null   int64
 21  Therapy History                    203 non-null    object
dtypes: float64(6), int64(8), object(8)
memory usage: 349.0+ KB

In [29]:
df.describe()

,Age,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Stress Level (1-10),Heart Rate (bpm),Breathing Rate (breaths/min),Sweating Level (1-5),Therapy Sessions (per month),Diet Quality (1-10),Anxiety Level (1-10),Target,is_Anxious
count,1968.000000,1994.000000,2030.000000,1936.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,2030.000000,1952.000000,2030.000000,2030.000000,2030.000000
mean,39.921748,6.424624,2.800246,306.275826,9.490148,6.028571,93.066502,20.955665,3.095567,2.359113,5.234119,3.922660,0.103448,0.103448
std,13.243754,2.161544,2.233899,208.012717,6.028653,3.137269,23.313430,5.182524,1.392697,2.148642,2.884946,2.139176,0.304619,0.304619
min,18.000000,-10.000000,-10.000000,0.000000,-10.000000,1.000000,60.000000,12.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,29.000000,5.800000,1.400000,177.750000,5.000000,3.000000,76.000000,17.000000,2.000000,1.000000,3.000000,2.000000,0.000000,0.000000
50%,40.000000,6.700000,2.800000,277.500000,10.000000,6.000000,93.000000,21.000000,3.000000,2.000000,5.000000,4.000000,0.000000,0.000000
75%,51.000000,7.500000,4.200000,391.000000,15.000000,9.000000,107.000000,26.000000,4.000000,3.000000,8.000000,5.000000,0.000000,0.000000
max,64.000000,11.000000,9.200000,1500.000000,19.000000,15.000000,220.000000,29.000000,5.000000,10.000000,10.000000,10.000000,1.000000,1.000000

In [30]:
df.isnull().sum()
#Age,Gender,sleep,caffeine,smoking,medication,diet,therapy

Age                                    62
Gender                                119
Occupation                              0
Sleep Hours                            36
Physical Activity (hrs/week)            0
Caffeine Intake (mg/day)               94
Alcohol Consumption (drinks/week)       0
Smoking                               106
Family History of Anxiety               0
Stress Level (1-10)                     0
Heart Rate (bpm)                        0
Breathing Rate (breaths/min)            0
Sweating Level (1-5)                    0
Dizziness                               0
Medication                            109
Therapy Sessions (per month)            0
Recent Major Life Event                 0
Diet Quality (1-10)                    78
Anxiety Level (1-10)                    0
Target                                  0
is_Anxious                              0
Therapy History                      1827
dtype: int64

In [31]:
df[df['Therapy History'].notna()]

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),...,Sweating Level (1-5),Dizziness,Medication,Therapy Sessions (per month),Recent Major Life Event,Diet Quality (1-10),Anxiety Level (1-10),Target,is_Anxious,Therapy History
0,59.0,Other,Teacher,7.0,2.4,40.0,5,Yes,No,4,...,5,No,No,0,Yes,1.0,2.0,0,0,Group Therapy
14,52.0,Other,Scientist,4.1,3.8,467.0,9,No,Yes,10,...,1,No,Yes,5,No,10.0,5.0,0,0,Psychodynamic Therapy
30,56.0,Male,Freelancer,6.5,4.8,124.0,17,Yes,No,10,...,4,No,Yes,0,No,4.0,5.0,0,0,Group Therapy
32,37.0,Other,Teacher,7.6,3.0,171.0,17,No,Yes,10,...,4,Yes,Yes,2,No,3.0,5.0,0,0,Psychodynamic Therapy
67,30.0,Other,Teacher,9.1,5.4,146.0,5,No,No,3,...,1,Yes,No,0,No,4.0,1.0,0,0,Group Therapy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,19.0,Female,Other,8.1,6.3,54.0,1,Yes,No,5,...,4,No,No,1,No,2.0,2.0,0,0,Psychodynamic Therapy
2000,43.0,Other,Chef,6.5,2.5,163.0,9,Yes,Yes,4,...,4,No,Yes,2,No,8.0,2.0,0,0,Cognitive Behavioral Therapy (CBT)
2006,NaN,Male,Freelancer,8.0,1.2,NaN,8,No,No,4,...,5,No,No,0,No,NaN,1.0,0,0,Group Therapy
2012,NaN,Male,Musician,6.2,4.9,193.0,18,Yes,Yes,3,...,5,Yes,No,1,Yes,5.0,1.0,0,0,No previous history
2026,34.0,Other,Freelancer,8.4,2.0,239.0,14,No,No,7,...,2,No,Yes,0,No,5.0,4.0,0,0,No previous history

In [32]:
df=df.drop(columns=["Therapy History"])

In [33]:
columns = {
    "numeric": [
        "Age",
        "Sleep Hours",
        "Physical Activity (hrs/week)",
        "Caffeine Intake (mg/day)",
        "Alcohol Consumption (drinks/week)",
        "Heart Rate (bpm)",
        "Breathing Rate (breaths/min)",
        "Therapy Sessions (per month)"
    ],

    "ordinal": [
        "Stress Level (1-10)",
        "Sweating Level (1-5)",
        "Diet Quality (1-10)",
        "Anxiety Level (1-10)"
    ],

    "categorical": [
        "Gender",
        "Occupation",
        "Smoking",
        "Family History of Anxiety",
        "Dizziness",
        "Medication",
        "Recent Major Life Event"
    ],

    "target": [
        "Target",
        "is_Anxious"
    ]
}

In [34]:
def negative_to_nan(df):
    df = df.copy()

    numeric_cols = df.select_dtypes(include=["number"]).columns

    for col in numeric_cols:
        df.loc[df[col] < 0, col] = np.nan

    return df

In [35]:
def outliers_numeric(df, cols):
    df = df.copy()

    for col in cols:

        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        df.loc[(df[col] < lower) | (df[col] > upper), col] = np.nan

    return df

#--

In [36]:
def clean_ordinal(df, cols):
    df = df.copy()

    ordinal_ranges = {
        "Stress Level (1-10)": (1, 10),
        "Diet Quality (1-10)": (1, 10),
        "Anxiety Level (1-10)": (1, 10),
        "Sweating Level (1-5)": (1, 5)
    }

    for col in cols:
        if col in ordinal_ranges:
            low, high = ordinal_ranges[col]
            df.loc[(df[col] < low) | (df[col] > high), col] = np.nan

    return df

In [37]:
def clean_categorical(df, cols):
    df = df.copy()

    for col in cols:
        df[col] = df[col].fillna("Unknown")

    return df

#--

In [38]:
df=negative_to_nan(df)

In [39]:
df=outliers_numeric(df,columns["numeric"])
df=clean_ordinal(df,columns["ordinal"])
df=clean_categorical(df,columns["categorical"])

In [40]:
df.isna().sum()

Age                                   62
Gender                                 0
Occupation                             0
Sleep Hours                           96
Physical Activity (hrs/week)          48
Caffeine Intake (mg/day)             124
Alcohol Consumption (drinks/week)     40
Smoking                                0
Family History of Anxiety              0
Stress Level (1-10)                   30
Heart Rate (bpm)                      30
Breathing Rate (breaths/min)           0
Sweating Level (1-5)                   0
Dizziness                              0
Medication                             0
Therapy Sessions (per month)         119
Recent Major Life Event                0
Diet Quality (1-10)                   78
Anxiety Level (1-10)                   0
Target                                 0
is_Anxious                             0
dtype: int64

In [41]:
def fillna_numeric(df, cols):
    df = df.copy()

    for col in cols:

        skew = df[col].skew()

        if abs(skew) < 0.5:
            df[col] = df[col].fillna(df[col].mean())
        else:
            df[col] = df[col].fillna(df[col].median())

    return df

In [42]:
def fillna_ordinal(df, cols):
    df = df.copy()

    for col in cols:
        df[col] = df[col].fillna(df[col].median())

    return df

In [43]:
df=fillna_numeric(df,columns["numeric"])
df=fillna_ordinal(df,columns["ordinal"])

In [44]:
df.isna().sum()

Age                                  0
Gender                               0
Occupation                           0
Sleep Hours                          0
Physical Activity (hrs/week)         0
Caffeine Intake (mg/day)             0
Alcohol Consumption (drinks/week)    0
Smoking                              0
Family History of Anxiety            0
Stress Level (1-10)                  0
Heart Rate (bpm)                     0
Breathing Rate (breaths/min)         0
Sweating Level (1-5)                 0
Dizziness                            0
Medication                           0
Therapy Sessions (per month)         0
Recent Major Life Event              0
Diet Quality (1-10)                  0
Anxiety Level (1-10)                 0
Target                               0
is_Anxious                           0
dtype: int64

In [45]:
df["Occupation"].unique()

array(['Teacher', 'Student', 'Lawyer', 'Nurse', 'Other', 'Musician',
       'Engineer', 'Artist', 'Chef', 'Scientist', 'Athlete', 'Freelancer',
       'Doctor'], dtype=object)

In [46]:
def encode_categorical(df):
    df = df.copy()

    if "Gender" in df.columns:
        df["Gender"] = df["Gender"].map({
            "Male": 0,
            "Female": 1,
            "Unknown": -1
        })

    binary_map = {
        "Yes": 1,
        "No": 0,
        "Unknown": -1
    }

    binary_cols = [
        "Smoking",
        "Family History of Anxiety",
        "Dizziness",
        "Medication",
        "Recent Major Life Event"
    ]

    for col in binary_cols:
        if col in df.columns:
            df[col] = df[col].map(binary_map)

    if "Occupation" in df.columns:
        occupation_map = {
            'Teacher': 0,
            'Student': 1,
            'Lawyer': 2,
            'Nurse': 3,
            'Other': 4,
            'Musician': 5,
            'Engineer': 6,
            'Artist': 7,
            'Chef': 8,
            'Scientist': 9,
            'Athlete': 10,
            'Freelancer': 11,
            'Doctor': 12
        }

        df["Occupation"] = df["Occupation"].map(occupation_map)
    return df

In [47]:
df=encode_categorical(df)

In [48]:
def bining_features(df):
    df = df.copy()

    bin_config = {

        "Age": (
            [0, 18, 30, 50, 120],
            ["Teen", "Young Adult", "Adult", "Senior"]
        ),

        "Sleep Hours": (
            [0, 5, 7, 9, 24],
            ["Sleep Deprived", "Normal Sleep", "Healthy Sleep", "Oversleeping"]
        ),

        "Physical Activity (hrs/week)": (
            [-1, 2, 5, 100],
            ["Non-Athletic", "Moderately Active", "Athletic"]
        ),

        "Caffeine Intake (mg/day)": (
            [-1, 100, 300, 600, 2000],
            ["Low", "Moderate", "High", "Coffee Addict"]
        ),

        "Alcohol Consumption (drinks/week)": (
            [-1, 0, 5, 10, 100],
            ["None", "Light", "Moderate", "Heavy"]
        ),

        "Heart Rate (bpm)": (
            [0, 60, 100, 200],
            ["Low", "Normal", "High"]
        ),

        "Breathing Rate (breaths/min)": (
            [0, 12, 20, 100],
            ["Slow", "Normal", "Rapid"]
        ),

        "Therapy Sessions (per month)": (
            [-1, 0, 2, 5, 20],
            ["No Therapy", "Occasional", "Regular", "Intensive"]
        ),

        "Stress Level (1-10)": (
            [0, 3, 6, 10],
            ["Low Stress", "Moderate Stress", "High Stress"]
        ),

        "Diet Quality (1-10)": (
            [0, 3, 6, 8, 10],
            ["Unhealthy", "Average", "Healthy", "Excellent"]
        ),

        "Anxiety Level (1-10)": (
            [0, 3, 6, 10],
            ["Low Anxiety", "Moderate Anxiety", "High Anxiety"]
        )

    }

    for col in bin_config:

        bins, labels = bin_config[col]

        df["Binned_",col ] = pd.cut(
            df[col],
            bins=bins,
            labels=labels
        )
    return df

In [49]:
df=bining_features(df)

In [50]:
df

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),...,"(Binned_, Sleep Hours)","(Binned_, Physical Activity (hrs/week))","(Binned_, Caffeine Intake (mg/day))","(Binned_, Alcohol Consumption (drinks/week))","(Binned_, Heart Rate (bpm))","(Binned_, Breathing Rate (breaths/min))","(Binned_, Therapy Sessions (per month))","(Binned_, Stress Level (1-10))","(Binned_, Diet Quality (1-10))","(Binned_, Anxiety Level (1-10))"
0,59.0,NaN,0,7.0,2.4,40.0,5.000000,1,0,4.0,...,Normal Sleep,Moderately Active,Low,Light,Normal,Rapid,No Therapy,Moderate Stress,Unhealthy,Low Anxiety
1,46.0,1.0,1,5.1,5.4,156.0,11.000000,-1,0,3.0,...,Normal Sleep,Athletic,Moderate,Heavy,Normal,Normal,Occasional,Low Stress,Unhealthy,Moderate Anxiety
2,40.0,NaN,2,5.1,1.9,570.0,14.000000,1,1,9.0,...,Normal Sleep,Non-Athletic,High,Heavy,High,Rapid,Intensive,High Stress,Average,High Anxiety
3,40.0,0.0,3,7.6,0.9,129.0,0.000000,0,0,9.0,...,Healthy Sleep,Non-Athletic,Moderate,None,High,Normal,Occasional,High Stress,Unhealthy,Moderate Anxiety
4,26.0,0.0,4,6.7,3.0,64.0,13.000000,0,0,6.0,...,Normal Sleep,Moderately Active,Low,Heavy,High,Normal,No Therapy,Moderate Stress,Average,Low Anxiety
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025,42.0,0.0,0,3.7,2.9,113.0,18.000000,1,1,4.0,...,Sleep Deprived,Moderately Active,Moderate,Heavy,Normal,Normal,Occasional,Moderate Stress,Unhealthy,Low Anxiety
2026,34.0,NaN,11,8.4,2.0,239.0,14.000000,0,0,7.0,...,Healthy Sleep,Non-Athletic,Moderate,Heavy,Normal,Normal,No Therapy,High Stress,Average,Moderate Anxiety
2027,62.0,1.0,5,6.1,1.6,149.0,18.000000,1,0,2.0,...,Normal Sleep,Non-Athletic,Moderate,Heavy,Normal,Rapid,Regular,Low Stress,Healthy,Low Anxiety
2028,47.0,NaN,3,6.3,1.1,298.0,9.786432,0,1,7.0,...,Normal Sleep,Non-Athletic,Moderate,Moderate,Normal,Rapid,Occasional,High Stress,Unhealthy,Moderate Anxiety
2029,44.0,1.0,6,6.0,7.9,268.0,3.000000,0,1,7.0,...,Normal Sleep,Athletic,Moderate,Light,Normal,Rapid,Regular,High Stress,Average,Moderate Anxiety